import type {
  Application,
  Category,
  Notif,
  Opportunity,
  Review,
  Student,
  Txn,
} from "./types";

export const CATEGORIES: Category[] = [
  "Web Development",
  "Design",
  "Writing",
  "Video",
  "Social Media",
  "Marketing",
  "Research",
  "Tutoring",
  "Photography",
  "Event Assistance",
  "Delivery",
  "Cleaning",
  "Moving",
  "Pet Care",
  "Babysitting",
  "Errands",
  "Other",
];

export const SKILL_OPTIONS = [
  "React",
  "JavaScript",
  "Python",
  "Graphic Design",
  "UI/UX",
  "Figma",
  "Writing",
  "Video Editing",
  "Social Media",
  "Marketing",
  "Photography",
  "Tutoring",
  "Research",
  "Data Entry",
  "Spreadsheets",
  "Customer Service",
  "Other",
];

export const TASK_TYPES = [
  "Walk dogs",
  "Babysit",
  "Clean apartments",
  "Help someone move",
  "Run errands",
  "Deliver items",
  "Assist at events",
  "Take photos",
  "Build websites",
  "Design graphics",
  "Manage social media",
  "Tutor students",
  "Edit video",
  "Write articles",
  "Transcribe audio",
  "Enter data",
  "Fix a laptop",
  "Assemble furniture",
  "Paint a room",
  "Cook for an event",
  "Drive someone",
  "Water plants",
  "Staff a stand",
  "Print and mount posters",
];

export const MODES = ["Remote", "On campus", "Local", "Hybrid"] as const;

export const DEMO_STUDENT: Student = {
  name: "Amara Okonkwo",
  avatar: "/img/avatar-1.jpg",
  university: "University of Lagos",
  course: "Computer Science",
  gradYear: 2027,
  studentEmail: "a.okonkwo@student.unilag.edu.ng",
  studentId: "UNILAG/CSC/22/0417",
  location: "Akoka, Lagos",
  bio:
    "Third-year computer science student. I build small web products for local businesses and shoot event photos on weekends. Fast replies, clear scope, no surprises.",
  skills: ["React", "JavaScript", "Figma", "Photography", "Writing"],
  rating: 4.9,
  reviewCount: 12,
  completedCount: 18,
  completionRate: 96,
  earnedTotal: 1240,
};

export const OPPORTUNITIES: Opportunity[] = [
  {
    id: "t-react-landing",
    kind: "task",
    title: "Need a React developer for a landing page",
    org: "Bright Bakery",
    orgKind: "Business",
    category: "Web Development",
    summary: "One-page site for a bakery that takes orders by phone every morning.",
    description:
      "We sell bread and pastry from two shops in town and we take orders by phone every morning. We need a single page that shows the menu, the two shop addresses and an order button that opens WhatsApp. It should load fast on a phone. Content and photos are ready; we just need it built and put online.",
    pay: { amount: 150, unit: "fixed" },
    mode: "Remote",
    location: "Remote, client on the other side of town",
    skills: ["React", "JavaScript", "CSS"],
    requirements: [
      "One page, mobile-first, loads under 2s on 3G",
      "WhatsApp order link with the menu items filled in",
      "Handover of the code and a short note on how to edit the menu",
    ],
    postedDaysAgo: 0,
    deadlineDays: 6,
    match: 92,
    matchReasons: [
      "Matches your React and JavaScript skills",
      "Remote, so it fits around lectures",
      "Fixed budget is above your $100 threshold",
    ],
    urgent: true,
  },
  {
    id: "t-dog-walker",
    kind: "task",
    title: "Dog walker needed on Tuesday and Thursday",
    org: "Mrs. Adeyemi",
    orgKind: "Student",
    category: "Pet Care",
    summary: "A small dog, two walks a week, five minutes from the Akoka gate.",
    description:
      "My dog Bingo is small and friendly and needs a walk at 4pm on Tuesdays and Thursdays while I am in a lecture. The route is around the estate, about 30 minutes. I would like someone who lives close to campus and is happy to send a photo when they get back.",
    pay: { amount: 25, unit: "fixed" },
    mode: "Local",
    location: "Akoka estate, 2 km from campus",
    skills: ["Reliability"],
    postedDaysAgo: 1,
    deadlineDays: 3,
    match: 67,
    matchReasons: ["2 km from your campus", "Fits your Tuesday and Thursday gaps"],
  },
  {
    id: "t-social-assistant",
    kind: "task",
    title: "Social media assistant for a campus cafe",
    org: "The Reading Room",
    orgKind: "Business",
    category: "Social Media",
    summary: "Four posts a week, filmed and posted from the cafe.",
    description:
      "We are a cafe opposite the main gate. We need someone to come in twice a week, film short clips of drinks being made, and post them on Instagram and TikTok. We will pay weekly. You should be comfortable on camera sometimes but mostly it is filming the counter.",
    pay: { amount: 80, unit: "per week" },
    mode: "On campus",
    location: "Main gate, opposite campus",
    skills: ["Social Media", "Video Editing"],
    postedDaysAgo: 0,
    deadlineDays: 4,
    match: 84,
    matchReasons: [
      "On campus, between lectures",
      "Recurring weekly pay",
      "Uses your video editing skill",
    ],
  },
  {
    id: "t-event-photographer",
    kind: "task",
    title: "Student event photographer for a faculty dinner",
    org: "Faculty of Science",
    orgKind: "University",
    category: "Photography",
    summary: "Three hours on a Saturday evening, edited photos delivered in a week.",
    description:
      "The Faculty of Science is holding its annual dinner for final-year students. We need one photographer for three hours. You keep your files, we need 60 edited photos delivered within a week for the yearbook and the faculty page.",
    pay: { amount: 100, unit: "fixed" },
    mode: "On campus",
    location: "Faculty hall, main campus",
    skills: ["Photography", "Photo Editing"],
    postedDaysAgo: 2,
    deadlineDays: 9,
    match: 88,
    matchReasons: ["Matches your photography skill", "On campus", "Weekend, no clash with lectures"],
  },
  {
    id: "t-website-designer",
    kind: "task",
    title: "Website designer for a student-run fashion label",
    org: "Ada Studio",
    orgKind: "Startup",
    category: "Design",
    summary: "Five screens for a label that sells at campus markets.",
    description:
      "We make and sell clothes at the Saturday campus market. Our Instagram is doing well but we need a simple site: home, shop, about, size guide and contact. We have a logo and photos. We want the design first, in Figma, then hand it to a developer.",
    pay: { amount: 200, unit: "fixed" },
    mode: "Remote",
    location: "Remote, team on campus",
    skills: ["Figma", "UI/UX", "Graphic Design"],
    postedDaysAgo: 3,
    deadlineDays: 12,
    match: 90,
    matchReasons: ["Matches your Figma skill", "Remote", "Portfolio piece for your profile"],
  },
  {
    id: "t-math-tutor",
    kind: "task",
    title: "Maths tutor for two first-year students",
    org: "Aisha B.",
    orgKind: "Student",
    category: "Tutoring",
    summary: "Two evenings a week, on campus, MTH101 and MTH102.",
    description:
      "My cousin and I are struggling with first-year maths and we would like someone who has already passed MTH101 and MTH102. Two evenings a week, an hour each, in the library. We would rather pay per hour and start this week.",
    pay: { amount: 15, unit: "per hour" },
    mode: "On campus",
    location: "Main library, floor 3",
    skills: ["Tutoring", "Mathematics"],
    postedDaysAgo: 1,
    deadlineDays: 5,
    match: 74,
    matchReasons: ["On campus", "Evenings", "Recurring work"],
  },
  {
    id: "t-moving-help",
    kind: "task",
    title: "Two people to help move a room on Saturday",
    org: "Kelechi N.",
    orgKind: "Student",
    category: "Moving",
    summary: "Three hours, ground floor to second floor, no stairs at the start.",
    description:
      "Moving out of my room into a flat nearby. Everything is packed in boxes already. We need two people to carry boxes and a small fridge. A van is booked; we just need hands for about three hours on Saturday morning.",
    pay: { amount: 40, unit: "fixed" },
    mode: "Local",
    location: "Akoka, 1 km from campus",
    skills: ["Physical work"],
    postedDaysAgo: 0,
    deadlineDays: 2,
    match: 61,
    matchReasons: ["Near campus", "Saturday morning"],
  },
  {
    id: "t-clean-apartment",
    kind: "task",
    title: "Clean a two-bedroom flat before handover",
    org: "Tunde A.",
    orgKind: "Student",
    category: "Cleaning",
    summary: "One afternoon, materials provided, inspection is the next morning.",
    description:
      "Handing back a rented flat and the agent is coming to inspect. I need someone thorough: kitchen, two bathrooms, floors and windows. Cleaning materials are already there. It should take four to five hours.",
    pay: { amount: 35, unit: "fixed" },
    mode: "Local",
    location: "3 km from campus",
    skills: ["Cleaning"],
    postedDaysAgo: 2,
    deadlineDays: 4,
    match: 58,
    matchReasons: ["Close to campus", "Afternoon work"],
  },
  {
    id: "t-errands-dashboard",
    kind: "task",
    title: "Build a simple dashboard for a farmer cooperative",
    org: "Green Basket Co-op",
    orgKind: "NGO",
    category: "Web Development",
    summary: "A table, a filter and a monthly total. Really.",
    description:
      "We record what each of our 60 farmers brings in every week in a notebook. We want a small internal page where our secretary can type entries and see a monthly total per farmer. No accounts needed, one password for the office laptop.",
    pay: { amount: 120, unit: "fixed" },
    mode: "Hybrid",
    location: "Nakuru, two visits, otherwise remote",
    skills: ["JavaScript", "Spreadsheets", "Data Entry"],
    postedDaysAgo: 4,
    deadlineDays: 15,
    match: 79,
    matchReasons: ["Uses your JavaScript skill", "Mostly remote", "Two visits covered"],
  },
  {
    id: "t-delivery-market",
    kind: "task",
    title: "Delivery rider for campus market day",
    org: "Campus Market",
    orgKind: "Business",
    category: "Delivery",
    summary: "Saturday, deliveries inside campus and to the two nearby estates.",
    description:
      "We run the Saturday market on the sports field. Orders are placed by phone and we need two riders to take them out between 10am and 4pm. You need your own bike or bicycle and a phone with data.",
    pay: { amount: 30, unit: "fixed" },
    mode: "On campus",
    location: "Sports field, main campus",
    skills: ["Delivery", "Reliability"],
    postedDaysAgo: 1,
    deadlineDays: 6,
    match: 63,
    matchReasons: ["On campus", "One-day work"],
  },
  {
    id: "j-part-time-barista",
    kind: "job",
    title: "Part-time barista, mornings",
    org: "The Reading Room",
    orgKind: "Business",
    category: "Other",
    summary: "Monday to Friday, 6:30am to 10:30am, before your first lecture.",
    description:
      "We need someone dependable for the morning shift: set up, take orders, make coffee on a two-group machine, clean down. Training is two days and paid. You must be able to start at 6:30am and have a lecture-safe schedule.",
    pay: { amount: 200, unit: "per week" },
    mode: "On campus",
    location: "Main gate, opposite campus",
    skills: ["Customer Service", "Reliability"],
    requirements: ["Available 6:30am to 10:30am, weekdays", "Two-day paid training"],
    duration: "Ongoing, semester by semester",
    postedDaysAgo: 1,
    deadlineDays: 8,
    match: 71,
    matchReasons: ["On campus", "Finishes before lectures", "Recurring income"],
  },
  {
    id: "j-campus-library-assistant",
    kind: "job",
    title: "Library assistant, evening shift",
    org: "University Library",
    orgKind: "University",
    category: "Other",
    summary: "Shelving, the front desk and helping students find material.",
    description:
      "The main library is recruiting two student assistants for the evening shift. Duties are shelving, the front desk, and helping students use the catalogue. Preference for students in their second year or above with a good academic standing.",
    pay: { amount: 90, unit: "per week" },
    mode: "On campus",
    location: "Main library, main campus",
    skills: ["Customer Service", "Research"],
    requirements: ["Second year or above", "Evening availability to 9pm"],
    duration: "One semester, renewable",
    postedDaysAgo: 3,
    deadlineDays: 11,
    match: 76,
    matchReasons: ["On campus", "Evenings", "University employer"],
  },
  {
    id: "j-remote-support",
    kind: "job",
    title: "Remote customer support, weekend shift",
    org: "Paylink",
    orgKind: "Startup",
    category: "Other",
    summary: "Answer chat tickets for a payments startup, 12 hours a week.",
    description:
      "We handle payouts for small businesses and the weekend queue is growing. You would answer chat tickets, follow the help centre, and escalate anything unusual. Written English matters more than experience. Laptop and data allowance provided.",
    pay: { amount: 220, unit: "per week" },
    mode: "Remote",
    location: "Remote",
    skills: ["Writing", "Customer Service"],
    requirements: ["12 hours across Saturday and Sunday", "Reliable internet"],
    duration: "Ongoing",
    postedDaysAgo: 2,
    deadlineDays: 10,
    match: 82,
    matchReasons: ["Remote", "Weekend, no lecture clash", "Strong weekly rate"],
  },
  {
    id: "j-campus-tour-guide",
    kind: "job",
    title: "Campus tour guide",
    org: "Admissions Office",
    orgKind: "University",
    category: "Other",
    summary: "Show visiting school students around campus, twice a week.",
    description:
      "We host school groups most weeks. We need confident students to lead tours of about 60 minutes, tell their own story about studying here, and answer questions. Training and a script are provided.",
    pay: { amount: 60, unit: "per week" },
    mode: "On campus",
    location: "Admissions building, main campus",
    skills: ["Customer Service", "Writing"],
    requirements: ["Comfortable speaking to groups of 20+", "Two mornings a week"],
    duration: "One semester",
    postedDaysAgo: 5,
    deadlineDays: 14,
    match: 69,
    matchReasons: ["On campus", "Mornings only", "Good for your confidence and CV"],
  },
  {
    id: "i-react-intern",
    kind: "internship",
    title: "Frontend intern (React)",
    org: "Northline Labs",
    orgKind: "Startup",
    category: "Web Development",
    summary: "Six months, hybrid, working on a logistics product used by 40 businesses.",
    description:
      "Northline Labs builds software for small logistics companies. As a frontend intern you will ship real features in a Next.js codebase: a customer dashboard, a driver view, and reports. You will have a mentor and a code review every week. We hire interns who want to stay on.",
    pay: { amount: 500, unit: "per month" },
    mode: "Hybrid",
    location: "Lisbon, three days a week",
    skills: ["React", "JavaScript", "CSS"],
    requirements: [
      "Portfolio or GitHub with at least one React project",
      "Available three days a week",
      "Final year or penultimate year preferred",
    ],
    duration: "6 months, starting next month",
    paid: true,
    postedDaysAgo: 2,
    deadlineDays: 13,
    match: 91,
    matchReasons: [
      "Direct match for React and JavaScript",
      "Hybrid, close to campus",
      "Converts to a graduate offer",
    ],
  },
  {
    id: "i-design-intern",
    kind: "internship",
    title: "Product design intern",
    org: "Caldera Health",
    orgKind: "Startup",
    category: "Design",
    summary: "Work on a clinic booking product used in 12 clinics.",
    description:
      "You will work with two designers on booking flows, a clinic dashboard and the patient app. Expect to run small research sessions, draw in Figma and hand off to engineers. We care about clear thinking more than a polished portfolio.",
    pay: { amount: 450, unit: "per month" },
    mode: "Remote",
    location: "Remote, team in Berlin",
    skills: ["Figma", "UI/UX"],
    requirements: ["Figma portfolio, three projects minimum", "Available 20 hours a week"],
    duration: "4 months, renewable",
    paid: true,
    postedDaysAgo: 4,
    deadlineDays: 16,
    match: 87,
    matchReasons: ["Matches your Figma and UI/UX skills", "Remote", "Strong portfolio piece"],
  },
  {
    id: "i-research-intern",
    kind: "internship",
    title: "Research intern, energy access",
    org: "Centre for Energy Studies",
    orgKind: "University",
    category: "Research",
    summary: "Fieldwork on solar mini-grids in two states, plus data cleaning.",
    description:
      "The centre is running an 18-month study on solar mini-grid usage. Interns help with survey design, field visits and cleaning the data. You will be named in the report if you stay for the full period. Useful if you are considering a masters.",
    pay: { amount: 300, unit: "per month" },
    mode: "On campus",
    location: "Campus, with two field trips",
    skills: ["Research", "Spreadsheets"],
    requirements: ["Comfortable with fieldwork", "Two days a week"],
    duration: "5 months",
    paid: true,
    postedDaysAgo: 6,
    deadlineDays: 18,
    match: 72,
    matchReasons: ["On campus", "Named in the published report", "Fits your research interest"],
  },
  {
    id: "i-marketing-intern",
    kind: "internship",
    title: "Growth marketing intern",
    org: "Harvest & Co.",
    orgKind: "Business",
    category: "Marketing",
    summary: "Own the content calendar for a food brand expanding to two new states.",
    description:
      "We make packaged snacks sold in 300 stores. The internship is content and community: a monthly calendar, short videos, and replies to customers. You will see how a marketing budget is actually spent and report on what worked.",
    pay: { amount: 380, unit: "per month" },
    mode: "Hybrid",
    location: "Rotterdam, two days on site",
    skills: ["Social Media", "Marketing", "Video Editing"],
    requirements: ["Own content you can show", "Two days on site"],
    duration: "6 months",
    paid: true,
    postedDaysAgo: 3,
    deadlineDays: 15,
    match: 78,
    matchReasons: ["Uses your social media and video skills", "Two days on site", "Paid internship"],
  },
  {
    id: "i-writing-intern",
    kind: "internship",
    title: "Editorial intern",
    org: "The Continental Review",
    orgKind: "Business",
    category: "Writing",
    summary: "Report on campus and city stories for a weekly paper.",
    description:
      "Our education desk covers campus news. Interns pitch, report and write two pieces a week with an editor. We will teach you interviewing and fact-checking. Published clips are yours to keep.",
    pay: { amount: 250, unit: "per month" },
    mode: "Hybrid",
    location: "London, one day on site",
    skills: ["Writing", "Research"],
    requirements: ["Two writing samples", "One day on site"],
    duration: "3 months",
    paid: true,
    postedDaysAgo: 1,
    deadlineDays: 12,
    match: 80,
    matchReasons: ["Matches your writing skill", "Published clips for your portfolio", "Mostly flexible"],
  },
];

export function findOpportunity(id: string) {
  return OPPORTUNITIES.find((o) => o.id === id);
}

export const DEMO_APPLICATIONS: Application[] = [
  {
    id: "a1",
    opportunityId: "t-social-assistant",
    stage: "In progress",
    updatedDaysAgo: 1,
    note: "Week 2 of 3. Two posts published so far.",
  },
  {
    id: "a2",
    opportunityId: "t-math-tutor",
    stage: "Accepted",
    updatedDaysAgo: 2,
    note: "First session agreed for Thursday, 6pm at the library.",
  },
  {
    id: "a3",
    opportunityId: "i-react-intern",
    stage: "Applied",
    updatedDaysAgo: 3,
  },
  {
    id: "a4",
    opportunityId: "t-website-designer",
    stage: "Submitted",
    updatedDaysAgo: 2,
    note: "Figma file delivered. Waiting on feedback.",
  },
  {
    id: "a5",
    opportunityId: "t-event-photographer",
    stage: "Completed",
    updatedDaysAgo: 6,
    note: "60 photos delivered. Awaiting payment release.",
    demoEscrow: true,
  },
  {
    id: "a6",
    opportunityId: "t-react-landing",
    stage: "Paid",
    updatedDaysAgo: 12,
    note: "Paid in full.",
  },
];

export const DEMO_TXNS: Txn[] = [
  {
    id: "tx1",
    label: "Landing page for Bright Bakery",
    amount: 150,
    kind: "earning",
    status: "Paid",
    date: "28 Sep",
    opportunityId: "t-react-landing",
    reference: "demo-ref-8f21",
    chain: "USDC",
  },
  {
    id: "tx2",
    label: "Social media assistant, week 1",
    amount: 80,
    kind: "earning",
    status: "Paid",
    date: "26 Sep",
    opportunityId: "t-social-assistant",
    reference: "demo-ref-71ac",
    chain: "USDC",
  },
  {
    id: "tx3",
    label: "Campus event photos",
    amount: 100,
    kind: "earning",
    status: "Paid",
    date: "19 Sep",
    opportunityId: "t-event-photographer",
    reference: "demo-ref-3b90",
    chain: "USDC",
  },
  {
    id: "tx4",
    label: "Maths tutoring, 4 sessions",
    amount: 60,
    kind: "earning",
    status: "Paid",
    date: "12 Sep",
    opportunityId: "t-math-tutor",
    reference: "demo-ref-1c44",
    chain: "USDC",
  },
  {
    id: "tx5",
    label: "Faculty dinner photos",
    amount: 100,
    kind: "pending",
    status: "Pending",
    date: "2 Oct",
    opportunityId: "t-event-photographer",
    chain: "USDC",
  },
  {
    id: "tx6",
    label: "Website design, Ada Studio",
    amount: 200,
    kind: "pending",
    status: "Pending",
    date: "3 Oct",
    opportunityId: "t-website-designer",
    chain: "USDC",
  },
  {
    id: "tx7",
    label: "Withdrawal to bank",
    amount: -25,
    kind: "withdrawal",
    status: "Settled",
    date: "30 Sep",
    chain: "USDC",
  },
];

export const DEMO_REVIEWS: Review[] = [
  {
    id: "r1",
    author: "Bright Bakery",
    avatar: "/img/avatar-2.jpg",
    rating: 5,
    text: "Amara understood the brief in one message and the page was live in four days. She also showed us how to change the menu ourselves.",
    opportunity: "Landing page",
    ago: "5 days ago",
  },
  {
    id: "r2",
    author: "Faculty of Science",
    avatar: "/img/avatar-3.jpg",
    rating: 5,
    text: "Turned up early, stayed late and the photos were better than what we paid for last year. Edited set arrived before the deadline.",
    opportunity: "Event photography",
    ago: "3 weeks ago",
  },
  {
    id: "r3",
    author: "Aisha B.",
    avatar: "/img/avatar-1.jpg",
    rating: 5,
    text: "Explained the topic until it actually made sense. My cousin passed the resit. We will book her again next semester.",
    opportunity: "Maths tutoring",
    ago: "1 month ago",
  },
  {
    id: "r4",
    author: "The Reading Room",
    avatar: "/img/avatar-2.jpg",
    rating: 4,
    text: "Good clips and the posts did well. One week the videos came a day late and we had to reshuffle.",
    opportunity: "Social media assistant",
    ago: "1 month ago",
  },
];

export const DEMO_NOTIFS: Notif[] = [
  {
    id: "n1",
    kind: "payment",
    title: "Payment released",
    body: "100.00 USDC for the faculty dinner photos has been released to your balance.",
    ago: "2h",
    unread: true,
  },
  {
    id: "n2",
    kind: "ai",
    title: "AI found 4 new matches",
    body: "Two React tasks and two remote internships match your saved search.",
    ago: "5h",
    unread: true,
  },
  {
    id: "n3",
    kind: "application",
    title: "You were accepted",
    body: "Aisha B. accepted your application for maths tutoring. Agree a first session.",
    ago: "1d",
    unread: true,
  },
  {
    id: "n4",
    kind: "deadline",
    title: "Deadline approaching",
    body: "The Bright Bakery landing page closes for applications in 6 days.",
    ago: "2d",
    unread: false,
  },
  {
    id: "n5",
    kind: "review",
    title: "New 5-star review",
    body: "Bright Bakery reviewed your landing page work. Your rating is now 4.9.",
    ago: "5d",
    unread: false,
  },
  {
    id: "n6",
    kind: "verification",
    title: "Student verification approved",
    body: "Your student record was confirmed. The verified badge is now on your profile.",
    ago: "2w",
    unread: false,
  },
];

export const AI_SOURCES = [
  {
    id: "boards",
    name: "Public job boards",
    detail: "Listings published for anyone to read, through their public pages and RSS feeds.",
    status: "live" as const,
  },
  {
    id: "careers",
    name: "Company career pages",
    detail: "Roles posted on company sites that allow indexing, read from their public pages.",
    status: "live" as const,
  },
  {
    id: "community",
    name: "Campus and community boards",
    detail: "University noticeboards, departmental mailing lists and neighbourhood groups.",
    status: "live" as const,
  },
  {
    id: "social",
    name: "Public social posts",
    detail: "Posts explicitly published as public, where the platform's terms allow reading.",
    status: "planned" as const,
  },
  {
    id: "partners",
    name: "Approved integrations",
    detail: "Data shared directly by employers and providers through an API we are allowed to use.",
    status: "planned" as const,
  },
];

export const COMING_SOON = {
  marketplace: {
    title: "Marketplace",
    tagline: "Buy, sell and exchange with students on your campus.",
    body:
      "Books, shoes, clothes, electronics, furniture and school materials, traded between students who are already verified. Same verification, same reputation, no strangers.",
    items: ["Textbooks", "Electronics", "Clothes and shoes", "Furniture", "Student services"],
  },
  scholarships: {
    title: "Scholarships",
    tagline: "Money that does not have to be repaid.",
    body:
      "Scholarships, grants, fellowships and competitions matched to your course, your year and where you are from, with the deadlines tracked for you.",
    items: ["Scholarships", "Grants", "Fellowships", "Competitions", "Deadlines and eligibility"],
  },
  social: {
    title: "Social",
    tagline: "The work students are doing, in public.",
    body:
      "Share what you built, find a collaborator for the weekend, and see who on your campus is good at the thing you need. Reputation you can point at.",
    items: ["Share work", "Find collaborators", "Discover students", "Share opportunities"],
  },
  offramp: {
    title: "Off-ramp",
    tagline: "USDC to the money in your pocket.",
    body:
      "Turn your balance into local currency straight to a bank account or mobile money, at a rate you can see before you confirm. Not switched on yet.",
    items: ["USDC", "Local currency", "Bank account", "Mobile money"],
  },
};

export const STUDENT_PROOF = [
  { id: "p1", name: "Tobi Adeleke", school: "UNILAG", earned: 980, tasks: 14 },
  { id: "p2", name: "Fatima Bello", school: "ABU Zaria", earned: 1450, tasks: 22 },
  { id: "p3", name: "Chidi Eze", school: "UNN", earned: 760, tasks: 9 },
];
